/*
 * File: Simulink_Timer_External_Functions.h
 *
 * Code generated for Simulink model :Simulink_Timer.
 *
 * Model version      : 1.4
 * Simulink Coder version    : 9.0 (R2018b) 24-May-2018
 * TLC version       : 9.0 (Aug 22 2018)
 * C/C++ source code generated on  : Fri Jan 15 16:12:16 2021
 *
 * Target selection: stm32.tlc
 * Embedded hardware selection: STM32CortexM
 * Code generation objectives: Unspecified
 * Validation result: Not run
 *
 *
 *
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */

#ifndef RTW_HEADER_Simulink_Timer_External_Functions_h_
#define RTW_HEADER_Simulink_Timer_External_Functions_h_

/* Generated by STM32_Config.*/
/***** External Imported Functions *****/
#endif                                 /* RTW_HEADER_Simulink_Timer_External_Functions_h_ */

/* File trailer for Real-Time Workshop generated code.
 *
 * [EOF] Simulink_Timer_External_Functions.h
 */
