/* 
 * File: Simulink_CAN_Loopback_External_Functions.h
 *  
 * Code generated for Simulink model :Simulink_CAN_Loopback.
 * 
 * Model version      : 1.161
 * Simulink Coder version    : 9.0 (R2018b) 24-May-2018
 * TLC version       : 9.0 (Aug 22 2018)
 * C/C++ source code generated on  : Sun Jan 17 15:35:46 2021
 * 
 * Target selection: stm32.tlc
 * Embedded hardware selection: STMicroelectronics->STM32 32-bit Cortex-M
 * Code generation objectives: 
 *    1. Execution efficiency
 *    2. RAM efficiency
 *    3. MISRA C:2012 guidelines
 * Validation result: Not run
 * 
 * 
 * 
 * ******************************************************************************
 * * attention
 * *
 * * THE PRESENT FIRMWARE WHICH IS FOR GUIDANCE ONLY AIMS AT PROVIDING CUSTOMERS
 * * WITH CODING INFORMATION REGARDING THEIR PRODUCTS IN ORDER FOR THEM TO SAVE
 * * TIME. AS A RESULT, STMICROELECTRONICS SHALL NOT BE HELD LIABLE FOR ANY
 * * DIRECT, INDIRECT OR CONSEQUENTIAL DAMAGES WITH RESPECT TO ANY CLAIMS ARISING
 * * FROM THE CONTENT OF SUCH FIRMWARE AND/OR THE USE MADE BY CUSTOMERS OF THE
 * * CODING INFORMATION CONTAINED HEREIN IN CONNECTION WITH THEIR PRODUCTS.
 * *
 * ******************************************************************************
 */



  #ifndef RTW_HEADER_Simulink_CAN_Loopback_External_Functions_h_
  #define RTW_HEADER_Simulink_CAN_Loopback_External_Functions_h_
    

                  /* Generated by STM32_Config.*/
                /***** External Imported Functions *****/




  


  


  


  


  


  


  


  


  


  


  


  


  


  


  


  


  


  


  


  


  #endif /* RTW_HEADER_Simulink_CAN_Loopback_External_Functions_h_ */
/* File trailer for Real-Time Workshop generated code.
 *
 * [EOF] Simulink_CAN_Loopback_External_Functions.h
 */
